version: '3'

services:

  nodejs:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: nodejs
    restart: always
    depends_on: 
      - mysql
    networks:
      - desafio-docker-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - nodejs
    networks:
      - desafio-docker-net

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    volumes: 
      - ${PWD}/mysql/data/:/var/lib/mysql
      - ${PWD}/mysql/init/:/docker-entrypoint-initdb.d/:ro
    environment: 
      - MYSQL_DATABASE=desafiodb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - desafio-docker-net

networks:
  desafio-docker-net:
    driver: bridge